RHCLOUD-18530: Send org-id to inventory
RedHatInsights/cloud-connector pull request #135
Opened 2022-04-04 15:02 UTC by aleccohan

## What?
Start sending the OrgID to inventory when hosts are created / updated.

## Why?
With the shift from EBS account-numbers to OrgID we should now be propagating the OrgID to all connected services alongside the Account number.

## How?
Added the "org_id" field to the host data being sent to the inventory topic.

## Testing
It looks like there are already tests in place that look for the OrgID.

## Anything Else?
JIRA:  https://issues.redhat.com/browse/RHCLOUD-18530

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2022-04-05 13:44 UTC, dehort requested changes
Hey @aleccohan!  This looks good to me.  Would you have a minute to add a quick check for the "org_id" field in the [validateInventoryMessage()](https://github.com/RedHatInsights/cloud-connector/blob/master/internal/controller/connected_client_recorder_test.go#L207) method in the tests?  If not, no worries I can add it.

2022-04-05 13:59 UTC, aleccohan commented
You betcha!!  Thanks for the review!  i'll go ahead and add that now!

2022-04-05 14:20 UTC, aleccohan commented
@dehort added!

2022-04-06 14:29 UTC, dehort approved these changes
Looks good to me!

2022-04-06 14:31 UTC, merged