Unmarshaling response
RedHatInsights/cloud-connector pull request #217
Opened 2023-06-26 16:06 UTC by dscervantes

## What?
Explain what the change is linking any relevant JIRAs or Issues.
Unmarshaling response 
https://issues.redhat.com/browse/RHCLOUD-21190

## Why?
Consider what business or engineering goal does this PR achieves.
Infrastructure are going to change the non- 200 response. We need to change the return error as an error instead of a string 

## How?
Created a new type that will send a json message 

## Testing
Did you add any tests for the change?

## Anything Else?
Any other notes about the PR that would be useful for the reviewer. 

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [X ] General Coding Practices

2023-06-27 20:03 UTC, dehort requested changes
Looking good!  I made a couple of comments.  Would you mind adding a couple of test cases to the existing tests in account_resolver_test.go?  We probably need a test for an empty json response, empty/invalid response and a valid response.

2023-06-27 20:03 UTC, dehort commented on internal/controller/account_resolver.go
> +type ErrorResponse struct {
Can you rename this to `authGwErrorResponse`?  Its a bit wordy but it communicates its use.

In golang, starting a variable with a capital letter exports the variable out of the package.  In this case, we do not need to expose the Gateway response structures outside of this package.  We really want to hide them from the callers.  So lets not export the error response and the non-error response (please change AuthGwResp to authGwResp).

2023-06-30 15:19 UTC, dscervantes commented on internal/controller/account_resolver.go
> +			return "", "", "", err
I saw the %w, but didn't know I could use it like that, makes a lot of sense !

2023-07-19 03:18 UTC, dehort commented
/retest

2023-07-21 18:51 UTC, merged